### ISSUE TITLE
Program says that custom .ogg file does not exist, despite the file existing and being placed in external content folder

### ISSUE THREAD

**Issue by waveblitzd** [ambiguousname/jackbox-custom-content#5]
The program says that the selected custom file does not exist whenever I select my .ogg audio file.

**Comment by ambiguousname** [comment]
Oh wow, I didn't realize anyone was still using this! Thanks for giving feedback. Would you mind sharing the .ogg audio file you're trying to upload, as well as the game you're trying to upload it to?

Same goes for https://github.com/ambiguousname/jackbox-custom-content/issues/6. If you could just share the sample images, I'd be happy to take a look.

Any screenshots of the dialogue box before you click "Ok" to try to create the content would also be useful. Selecting and creating content from .ogg files seems to work on my end, so any details you can provide would be super duper appreciated.

**Comment by waveblitzd** [comment]
Github doesn't support .ogg files apparently, so here is a link to the download: https://drive.google.com/file/d/1eMFxrC7io17tDb7r-guQqOUhbskBNc1w/view?usp=sharing . I put it through a .mp3 to .ogg converter if it helps to solve the issue, and the game is quiplash 3. 

for my turning points images, they're a bit silly and out of aspect ratio but other than that there's nothing up with the files from what I could tell. they're in .jpg format.

for some reason this isn't restricted to content I've created myself, some of the sample content included with the .zip had the "file does not exist" error occur when importing it

![eevee goes to war](https://user-images.githubusercontent.com/83782418/175192474-c6149499-440f-499b-9eec-70604ffa52ec.jpg)
![nectar](https://user-images.githubusercontent.com/83782418/175192475-97caece2-e25b-4a22-ae82-5498adaa07b7.jpg)
![image](https://user-images.githubusercontent.com/83782418/175192603-abbf23f7-2a68-401c-a83e-7a4d5ea06ff4.png)

**Comment by waveblitzd** [comment]
(oops, forgot to include quiplash 3 images)
![image](https://user-images.githubusercontent.com/83782418/175193167-789377ab-759b-46b2-8c94-87eb24afd89c.png)
aaand the displayed error as well 
![image](https://user-images.githubusercontent.com/83782418/175193219-cb7c8d06-a768-4d2f-810d-c0e69f5c2f14.png)

**Comment by ambiguousname** [comment]
Unfortunately, after a bit of a testing, I haven't been able to replicate this myself, which makes me think that the problem is dependent EITHER on how python uses `os.path.exists` in different systems (and their subsequently different file storage solutions), or how your file system is set up.

Python shooouuulllddd work regardless of OS system (especially if you're using `./` in front of all your file searches), and I've tested a few different file setups that work for me regardless (even dumb stuff, like adding `//` to each file name).

So, I have a few follow ups that should hopefully provide more insight:
1. How are you installing and running this? Is it through python or the downloadable executable from [Releases](https://github.com/ambiguousname/jackbox-custom-content/releases/tag/1.0.0) (ideally version 1.0.0)?
2. What operating system are you using? If it's anything other than Windows, that might be the source of conflict, and so I might have to re-write the `os.path.exists` functions to account for that.
3. Are you using the "Browse" button to select the files?
4. Does your .ogg file have read/write permissions enabled? The script might not be detecting the file if it isn't allowed to read it.

Thank you so much for your patience while I try to figure out what's going wrong!

**Comment by waveblitzd** [comment]
1. I installed the downloadable zip from releases and unpacked it to the games folder of my jackbox directory
2. I'm running windows 10
3. Yes, I'm using the "browse" button
4. Read and write permissions are active, but there was a check saying it was blocked from security for being from another computer? i changed the permission and applied it but the error's still happening.

**Comment by waveblitzd** [comment]
comment: after attempting a solution of moving the folder from downloads to an SSD, the error still persists.

**Comment by ambiguousname** [comment]
Alright, I'm still working on potential fixes/debugging, and my brain is somewhat drained for the day, so here are my last few stabs at figuring out what's wrong before I go to sleep and continue working on this tomorrow.

Instead of moving the whole external content folder somewhere else, I'd try moving a file out of there, maybe to your Desktop and importing it from there.

If you have python installed, you could try testing out how os.path.exists works on your computer in multiple cases:
```python
> python
>>> os.path.exists("C:\\Global\\Path\\To\\Filename")
Should return True
>>> os.path.exists("./external content/path/to/file")
Should return True
```
If any return false, it's probably a sign that I have to re-write the os.path.exists calls (something I'm working on right now, I should have a testable executable tomorrow).

You could also try uninstalling and reinstalling the whole thing if you haven't done already? Delete the executable and custom_content.json, delete the external content folder, and then validate the files through Steam (I assume you're using Steam).

Additionally, are there any files that get imported successfully?

**Comment by waveblitzd** [comment]
it appears none of the files imported successfully. the ones included in the custom content were given the error as well. 
appears that moving the content to a location that isn't in the jackbox directory works. seems to be the implied issue

**Comment by waveblitzd** [comment]
*after reinstalling the zip. moving the custom content to desktop worked just fine

**Comment by ambiguousname** [comment]
Just caught this, and that's great to hear! I think I know what's causing the issue, and I will create an appropriate fix for testing tomorrow. Thanks for your continued patience.

**Comment by waveblitzd** [comment]
no problem! love your program, makes it much easier to customize the game

**Comment by ambiguousname** [comment]
Alright, I believe the attached executable should fix the problem. Try importing a .ogg file from the external content folder in the games directory.

If all is well, I'll upload the patch as a release.

Here's the .ZIP file which contains the .exe:
[Jackbox Party Pack Custom.zip](https://github.com/ambiguousname/jackbox-custom-content/files/8972051/Jackbox.Party.Pack.Custom.zip)

**Comment by waveblitzd** [comment]
it worked! sorry for a late response

**Comment by ambiguousname** [comment]
Great, and no problem! I will close both issues and make a new release.
